#!/usr/bin/env bash

yarn run tsc

# Copy package.json to /dist
cp package.json dist/

# Copy node_modules to dist
cp -r node_modules dist/

cd dist

#  Remove dist/ paths
declare -a regmain=(
  's=dist/index.js=index.js=g'
  's=dist/index.d.ts=index.d.ts=g'
  's="prepare": "husky install"="prepare": ""=g'
)

## Perform the string replacements - "$OSTYPE" == "darwin" is Mac
for reg in "${regmain[@]}"
do 
  if [[ "$OSTYPE" == "darwin"* ]]; then
    sed -i '' "$reg" package.json
  else
    sed -i "$reg" package.json
  fi
done