#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# =========== Start from https://github.com/typicode/husky/issues/912#issuecomment-887840695
export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
# =========== End

npm install -g yarn
yarn run eslint:fix
yarn run stylelint
yarn run index
yarn test
yarn run clear-build-cache
yarn run build
yarn run build-docs
git add .