#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# =========== Start from https://github.com/typicode/husky/issues/912#issuecomment-887840695
export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
# =========== End

npm run eslint:fix
npm run stylelint
npm run index
npm test
npm run build-docs
git add .