name: CI

on:
  pull_request:
    branches: [master]

jobs:
  testOnIntegrate:
    runs-on: ubuntu-latest

    steps:
      # Setup node
      - name: Setup Node with the right version
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"

      # Checkout branch to merge
      - name: Checkout branch to merge
        uses: actions/checkout@v2

      # Install dependencies
      - run: yarn install

      # Run eslint test
      - name: Run ESLint test
        run: yarn run eslint

      # Run stylelint test
      - name: Run Stylelint test
        run: yarn run stylelint

      # Build and type check
      - name: Test build
        run: yarn run build

      # Check if docs are included
      - name: Check generated docs
        run: yarn run build-docs && yarn run git-check-unclean
